name: CI/CD - DevOps Fase 1 - React/Terraform/S3

on:
    push:
        branches: ["master"]
    workflow_dispatch:

jobs:
    #1 - Seguindo as orientações das aulas, estou seguindo as melhores práticas de CI/CD, irei realizar os testes e o build no ambiente do github antes.
    build-static:
        name: Validacao dos arquivos
        runs-on: ubuntu-latest
        steps:
            - name: Checkout do código
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test -- --watchAll=false

            - name: Audit packages
              run: npm audit --production --audit-level=moderate || true

            - name: Build
              run: npm run build

            - name: Verificar a pasta build
              run: ls -la build

            - name: Verificar se existe index.html
              run: |
                if [ ! -f build/index.html ]; then
                    echo "index.html não encontrado"
                    exit 1
                else
                    echo "index.html encontrado"
                fi

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                    name: build
                    path: build/

    #2 - Agora que o build foi validado, irei gerar a infra, começando com a validação do terraform
    terraform-validate:
        name: Validação e planejamento do Terraform
        needs: build-static
        runs-on: ubuntu-latest
        steps:
            - name: Checkout do código
              uses: actions/checkout@v4

            - name: Instalar Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.9.5

            - name: Iniciar Terraform
              working-directory: infra/terraform
              run: terraform init -input=false

            - name: Verificar formatação
              working-directory: infra/terraform
              run: terraform fmt -check

            - name: Validar configuração
              working-directory: infra/terraform
              run: terraform validate

            - name: Planejar infraestrutura
              working-directory: infra/terraform
              run: terraform plan -out=tfplan -var="project_name=hotwheels-frontend" -var="environment=dev" -var="aws_region=us-east-1" -var="enable_public_access=true"

            - name: Salvar plano como artefato
              uses: actions/upload-artifact@v4
              with:
                  name: tfplan
                  path: infra/terraform/tfplan